// ABOUTME: Types + loader for reading.json. The JSON is the source of truth; this file types it.
// ABOUTME: reading.json is generated by scripts/sync-reading.mjs from the second-brain vault — don't hand-edit finished/currentlyReading entries, re-run the script instead.

import readingData from './reading.json';

export interface CurrentlyReadingItem {
  title: string;
  author: string;
  /** Cover thumbnail — self-hosted under public/assets/images/reading/ by the sync script. */
  cover: string;
  /** ISO date (YYYY-MM-DD) the book was started. */
  started: string;
  series?: string;
  seriesNumber?: number;
  /** Blog post entry id (src/content/blog), when you've written about this book. */
  relatedPost?: string;
}

export interface FinishedItem {
  title: string;
  author: string;
  cover: string;
  /** ISO date (YYYY-MM-DD) the book was finished. */
  finished: string;
  /** Personal rating, out of 10 (even numbers in the source data). Absent for a handful of finished books. */
  rating?: number;
  format: 'book' | 'audiobook';
  series?: string;
  seriesNumber?: number;
  /** True only for books flagged `favorite: true` in the vault. */
  favorite?: boolean;
  /** Personal review note, HTML-stripped. Present on a minority of finished books. */
  review?: string;
  /** Blog post entry id (src/content/blog), when you've written about this book. */
  relatedPost?: string;
}

export interface ReadingData {
  currentlyReading: CurrentlyReadingItem[];
  finished: FinishedItem[];
}

export const reading: ReadingData = readingData as ReadingData;
