// ABOUTME: Types + lookup for webmentions.json. The JSON is the source of truth; this file types it and slices it per page.
// ABOUTME: webmentions.json is generated by scripts/sync-webmentions.mjs from the webmention.io feed — don't hand-edit it, re-run `bun run webmentions:sync`.

import webmentionsData from './webmentions.json';
import {
  normalizeTarget,
  isHiddenSelfResponse,
  type MentionProperty,
} from '../lib/webmentionTarget';

export interface MentionAuthor {
  /** Display name, or the source host when the sender is anonymous. */
  name: string;
  /** The author's own site or profile. */
  url?: string;
  /** Local path under public/ — self-hosted by the sync script, absent when the download failed. */
  photo?: string;
}

export interface Mention {
  /** webmention.io's `wm-id`. Stable, and what dedupe keys on. */
  id: number;
  type: MentionProperty;
  /** The source page — the reply, the post that linked here, the like. */
  url?: string;
  /** ISO timestamp; falls back to when webmention.io received it. */
  published?: string;
  author: MentionAuthor;
  /** Plain-text body. Absent on likes and reposts, which carry no content. */
  text?: string;
  /** The source's own title, when it has one (another blog post rather than a toot). */
  title?: string;
}

export interface TargetMentions {
  /** Replies and mentions — these have content, so they render as cards. */
  responses: Mention[];
  /** Likes, reposts and bookmarks — author only, so they render as a facepile. */
  reactions: Mention[];
}

export interface WebmentionsData {
  /** ISO timestamp of the last successful sync, or null before the first one. */
  syncedAt: string | null;
  /** Keyed by normalized target URL — see normalizeTarget. */
  targets: Record<string, TargetMentions>;
}

/** What a page needs to render its Responses region. */
export interface PageMentions extends TargetMentions {
  counts: {
    likes: number;
    reposts: number;
    bookmarks: number;
  };
  /** Total across both buckets — the "is there anything to show" check. */
  total: number;
}

const EMPTY: PageMentions = {
  responses: [],
  reactions: [],
  counts: { likes: 0, reposts: 0, bookmarks: 0 },
  total: 0,
};

export const webmentions: WebmentionsData = webmentionsData as WebmentionsData;

// Undated mentions sort last rather than to 1970, so a sender who omitted
// `published` doesn't jump to the top of the conversation.
function byPublishedAscending(a: Mention, b: Mention): number {
  const left = a.published ? Date.parse(a.published) : Number.POSITIVE_INFINITY;
  const right = b.published ? Date.parse(b.published) : Number.POSITIVE_INFINITY;
  return left - right;
}

/**
 * Every mention received for one page.
 *
 * The cache is keyed by normalized target, so pass any spelling of the page's
 * URL — canonical, with or without a trailing slash — and it resolves to the
 * same bucket. Returns empty rather than throwing for a page nobody has
 * mentioned, which is the common case.
 */
export function mentionsFor(url: string | URL): PageMentions {
  const key = normalizeTarget(typeof url === 'string' ? url : url.toString());
  if (!key) return EMPTY;

  const bucket = webmentions.targets[key];
  if (!bucket) return EMPTY;

  // My own POSSE announcements and self-likes stay in the committed archive but
  // never render. My own *replies* do render — they are the conversation. See
  // isHiddenSelfResponse.
  const shown = (mention: Mention) => !isHiddenSelfResponse(mention.author.url, mention.type);

  const responses = bucket.responses.filter(shown).sort(byPublishedAscending);
  const reactions = bucket.reactions.filter(shown);

  return {
    responses,
    reactions,
    counts: {
      likes: reactions.filter((m) => m.type === 'like-of').length,
      reposts: reactions.filter((m) => m.type === 'repost-of').length,
      bookmarks: reactions.filter((m) => m.type === 'bookmark-of').length,
    },
    total: responses.length + reactions.length,
  };
}
